# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  cadastroparceirosapi:
    image: cadastroparceirosapi
    build:
      context: .
      dockerfile: Cadastro.Parceiros.API/Dockerfile
    ports:
      - 5182:5182
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
